apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-ns
type: Opaque
data: # do not use these values in production
  db_user: cG9zdGdyZXM= # base64 encoded value of "postgres"
  db_password: cG9zdGdyZXM= # base64 encoded value of "postgres"
  db_dsn: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0B0ZWNoLWNoYWxsZW5nZS5jenZmbmt6aHhmdmEudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tL3Bvc3RncmVz" # base64 encoded value of "postgres://..."

# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
